import { useState } from "react";


const mockBooks = [
  {
    id: 1,
    title: "Atomic Habits",
    author: "James Clear",
    category: "Self-help",
    city: "Karachi",
    condition: "New",
    points: 50,
    image: "https://images-na.ssl-images-amazon.com/images/I/91bYsX41DVL.jpg",
  },
  {
    id: 2,
    title: "The Alchemist",
    author: "Paulo Coelho",
    category: "Fiction",
    city: "Lahore",
    condition: "Used",
    points: 30,
    image: "https://images-na.ssl-images-amazon.com/images/I/71aFt4+OTOL.jpg",
  },
  {
    id: 3,
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    category: "Fantasy",
    city: "Islamabad",
    condition: "New",
    points: 40,
    image: "https://images-na.ssl-images-amazon.com/images/I/81YOuOGFCJL.jpg",
  },
  {
    id: 4,
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki",
    category: "Finance",
    city: "Karachi",
    condition: "Used",
    points: 35,
    image: "https://images-na.ssl-images-amazon.com/images/I/81bsw6fnUiL.jpg",
  },
  {
    id: 5,
    title: "The Power of Now",
    author: "Eckhart Tolle",
    category: "Spirituality",
    city: "Lahore",
    condition: "New",
    points: 45,
    image: "https://images-na.ssl-images-amazon.com/images/I/71aFt4+OTOL._AC_UL600_SR600,600_.jpg",
  },
  {
    id: 6,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    category: "Classic",
    city: "Islamabad",
    condition: "Used",
    points: 25,
    image: "https://images-na.ssl-images-amazon.com/images/I/81OdwZ9pJPL.jpg",
  },
  {
    id: 7,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    category: "Fantasy",
    city: "Karachi",
    condition: "New",
    points: 50,
    image: "https://images-na.ssl-images-amazon.com/images/I/91b0C2YNSrL.jpg",
  },
  {
    id: 8,
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    category: "History",
    city: "Lahore",
    condition: "Used",
    points: 40,
    image: "https://images-na.ssl-images-amazon.com/images/I/713jIoMO3UL.jpg",
  },
  {
    id: 9,
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    category: "Self-help",
    city: "Islamabad",
    condition: "New",
    points: 35,
    image: "https://images-na.ssl-images-amazon.com/images/I/71QKQ9mwV7L.jpg",
  },
  {
    id: 10,
    title: "1984",
    author: "George Orwell",
    category: "Dystopian",
    city: "Karachi",
    condition: "Used",
    points: 30,
    image: "https://images-na.ssl-images-amazon.com/images/I/71kxa1-0mfL.jpg",
  },
  {
    id: 11,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    category: "Classic",
    city: "Lahore",
    condition: "New",
    points: 25,
    image: "https://images-na.ssl-images-amazon.com/images/I/81OthjkJBuL.jpg",
  },
  {
    id: 12,
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    category: "Psychology",
    city: "Islamabad",
    condition: "Used",
    points: 40,
    image: "https://images-na.ssl-images-amazon.com/images/I/71pA1rHhG-L.jpg",
  },
];

export default function useMockBooks() {
  const [books, setBooks] = useState(mockBooks);
  return { books, setBooks };
}
